### ISSUE TITLE
Feature Request: Show shortcut number near service icon

### ISSUE THREAD

**Issue by plan8studios** [wavebox/waveboxapp#514]
* Which version of Wavebox are you using? 3.7.0
* Which Operating System are you using? MacOS 10.13.2

It might be helpful to have the shortcut number under/above/near the service icon. I've got 11 things in Wavebox and after the 3rd or 4th one, it's tricky to figure out which one I want at a glance, so I have to take my hands off the keyboard and use the mouse to click the icon rather than using the CtrlOrCmd+# shortcut. I realize that switching with the shortcut is only possible up to the 9th service, so it could look weird to have the first 9 services display a number and all subsequent services would be missing that data.

**Comment by plan8studios** [comment]
It can be done with some simple css...

```css
.ReactComponent-Sidelist-Mailboxes{
   counter-reset: section;
}

.ReactComponent-Sidelist-Mailboxes > div:nth-child(-n+9):after{
    position: absolute;
    display: block;
    content: counter(section);
    right: 0;
    bottom: 0;
    color: #FFF;
    counter-increment: section
}
```

It doesn't look great, but it gets the numbers in there without any changes to the markup :-)

![image](https://user-images.githubusercontent.com/680706/34117767-ead9e41e-e3d9-11e7-8da1-76a1749a07bd.png)

**Comment by nmat** [comment]
Looks nice! If it is implemented a way to also "not" show them would probably make sense.

"Show service numbers"
"Show index service numbers"

As a example?

**Comment by Thomas101** [comment]
Hi, we’ve just released the ability to add custom css to the main Wavebox window. You can find this under the `Main Window Custom CSS` button in Advanced settings. If you want to add some custom styling such as this that's the place to do it!

You might need to update your selectors slightly as we've updated the UI now. I think `.ReactComponent-Sidelist-Mailboxes > div > div` should do it though. We're also going to be adding more classname support to our ui in an upcoming release so theming/styling will less brittle.

This is in the beta channel of Wavebox in version 3.7.1 at the moment. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by Thomas101** [comment]
@afail this isn't something we're looking at adding into the app at the moment - however if there's more demand for it, of course we'll take another look.

As for the original CSS posted above, the underlying UI and API have changed a little. I think the following should get you where you want to go....

```css
.WB-Sidelist-Mailboxes{
   counter-reset: section;
}

.WB-Sidelist-Mailboxes > div > div {
    position: relative;
}
.WB-Sidelist-Mailboxes > div > div:nth-child(-n+9):after{
    position: absolute;
    display: block;
    content: counter(section);
    right: 0;
    bottom: 0;
    color: #FFF;
    counter-increment: section
}
```
