### ISSUE TITLE
Support CSS variables for accounts/services colors for better CSS styling

### ISSUE THREAD

**Issue by rfgamaral** [wavebox/waveboxapp#866]
Before knowing about Wavebox I used Franz and overall I prefer the UI style for selected account:

![image](https://user-images.githubusercontent.com/96476/49368989-26498c80-f6e8-11e8-930b-4558cc79c88d.png)

I'm referring to the light blue background and blue left border. But I'd like to tweak this to go even further (which Franz doesn't allow at all), by using the account color instead of defaulting to blue for all accounts. Unfortunately, this is not currently possible.

To make this possible, we'd need to have access to color variables inside the CSS tweak box, preferably in RGB format so we could [apply transparency](https://stackoverflow.com/questions/29591465/use-css-variables-with-rgba-for-gradient-transparency). Although I'm not sure CSS variables are the way to go because we'd need to have a single variable for "account color" that would be replaced by the proper account color.

Currently I can tweak the little dot CSS and transform it into a border but I'd like to have a lighter background with the account color when the account is selected, and for that I need access to the account color inside the CSS tweak box.

Also, I don't think it's currently possible to apply a CSS tweak to the selected account only. We'd need a class (applied to selected account container only) to indicate that.

The same could be implemented for services for even further CSS styling.

Is this a lot of work? Could this be considered for a future version?

**Comment by Thomas101** [comment]
Ideally we should use [css attr](https://caniuse.com/#feat=css3-attr) variables, but browser support is still at 0%. With this we could get the app to just drop the colour into the dom as a data attribute and you're good to go.

What about if we I put the mailbox & service id along with the active state into the class name. You'd have to hard-code your colours into the css and you're selectors would be really long, but it would allow you to change them per account. For example...

![screenshot 2018-12-03 at 11 57 41](https://user-images.githubusercontent.com/103586/49372582-12575800-f6f3-11e8-8eef-3e8e03c4fc60.png)

You could style up as...
```css
.WB-SidelistItemServiceAvatar.WB-Id-724d1589-7f14-4821-8ec1-1f470204cf60-0c7da4b9-d61d-4072-9248-1cf67af2e9ec {
  background-color: rgba(255, 0, 0, 0.5);
}
.WB-SidelistItemServiceAvatar.WB-Id-724d1589-7f14-4821-8ec1-1f470204cf60-0c7da4b9-d61d-4072-9248-1cf67af2e9ec.WB-Active {
  background-color: rgba(255, 0, 0, 1.0);
}
```
...etc
